# ----
# Site

title: Zeynep Kandemir | Minyatür ve Osmanlı Minyatürü Sanatı | Miniature and Ottoman Miniature Art
description: Osmanlı minyatürü, Ottoman miniature, klasik minyatür sanatı, classic miniature art, geleneksel Türk sanatları ve el yapımı sanat eserleri üzerine bir rehber.
url: "https://zeynepkandemir.github.io/"
baseurl: "https://zeynepkandemir.github.io/"
google_analytics_key: "G-SGD8FF5BX4"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Photography portfolio template for Jekyll.
author: 
  name: Zeynep Kandemir
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Zeynep Kandemir
  links:
    - https://github.com/CloudCannon/aperture-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /uploads/1.jpg
  -
    scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true
